import selenium
from selenium import webdriver
from time import sleep
chrome = webdriver.Chrome(r"C:\Program Files\chromedriver.exe")
chrome.get("https://qasims.saxon.ky/Sims/(S(0vciitns3ckae0h4egjnq2ik))/Login.aspx")
sleep(2)
chrome.find_element_by_css_selector("#Login1_UserName")
uname = chrome.find_element_by_css_selector("#Login1_UserName")
uname.send_keys("Priya")
pwd = chrome.find_element_by_css_selector("#Login1_Password")
pwd.send_keys("Saxon2018!")
chrome.find_element_by_css_selector("#Login1_Button1").click()
sleep(1)
chrome.find_element_by_css_selector("#ctl00_btnNewClaim").click()
sleep(1)
chrome.switch_to.frame("GridEditor")
chrome.find_element_by_id("ctl03_ctl00_wizNewClaim_chkCoverageVerification").click()
loss_date=chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_rdpIncidentDate_dateInput")
loss_date.send_keys("Jun 14, 2020")
#chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_sppPolicy_tbPolicyPicker").click()
Policy_Picker = chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_sppPolicy_lnkPolicyPicker").click()
chrome.switch_to.frame("rwPolicyPicker")
inputElement = chrome.find_element_by_name("tbPolicyNumber")
inputElement.click()
inputElement.send_keys("P05062018-KY-051268")
chrome.find_element_by_css_selector("#btnOK").click()
sleep(1)
chrome.find_element_by_css_selector("#rgPolicy_ctl00_ctl04_btnSelect").click()
sleep(2)
chrome.switch_to.frame("GridEditor")
sleep(0.5)
chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_chkUseInsured").click()
chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_StartNavigationTemplateContainerID_btnNext").click()
sleep(1)
chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_StepNavigationTemplateContainerID_Button1").click()
chrome.find_element_by_css_selector("#alert1594927051521_content > div > div.rwDialogButtons > input").click()
time_picker = chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_txtInjuryTime_dateInput").click()
time_picker.send_keys("1:00 PM")
secondary_loss = chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_rdpIncidentDateSecondary_dateInput").click()
secondary_loss.send_keys("Jun 14, 2020")
loss_location = chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_addrLossLocationAddress_lnkAddress").click()
ad1 = chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_addrLossLocationAddress_txtAddress1").click()
ad1.send_keys("Street 305")

chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_addrLossLocationAddress_lnkAddress").click()

examin = chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_cboExaminer_Input").click()
examin.send_keys("priya")
claimant = chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_txtInjuryDescription").click()
claimant.send_keys("Vechile Damaged")
claimloss = chrome.find_element_by_css_selector("##ctl03_ctl00_wizNewClaim_txtClaimLossDesc").click()
claimloss.send_keys("Accident")
step3_next = chrome.find_element_by_css_selector("#ctl03_ctl00_wizNewClaim_StepNavigationTemplateContainerID_Button1").click()

#Insured_Name = chrome.find_element_by_css_selector("#tbInsuredName").click()
#custom_filter = chrome.find_element_by_css_selector("#tbFilter").click()
#custom_filter2 = chrome.find_element_by_css_selector("##tbFilter2").click()
#chrome.switch_to.frame("rwPolicyPicker")#tbPolicyNumber

